# Proje kimliği (SonarQube'de belirlediğin isimle aynı olmalı)
sonar.projectKey=FitRehber
sonar.projectName=FitRehber

# Kodların nerede olduğu
sonar.sources=.

# Hariç tutulacak klasörler (Bunları taratıp zaman kaybetme)
sonar.exclusions=**/*.bin,**/*.obj,**/*.dll,**/.git/**/*,**/node_modules/**/*,**/bin/**/*

# Dil ve Kodlama
sonar.sourceEncoding=UTF-8
sonar.language=cs,js,ts